USE [master]
GO

/****** Object:  Database [Agenda]    Script Date: 4/11/2024 11:50:36 AM ******/
IF EXISTS (SELECT name FROM sys.databases WHERE name = 'Agenda')
BEGIN
    ALTER DATABASE [Agenda] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [Agenda];
END
GO

/****** Object:  Database [Agenda]    Script Date: 4/11/2024 11:50:36 AM ******/
CREATE DATABASE [Agenda]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Agenda', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Agenda.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Agenda_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Agenda_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Agenda].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Agenda] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Agenda] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Agenda] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Agenda] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Agenda] SET ARITHABORT OFF 
GO

ALTER DATABASE [Agenda] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Agenda] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Agenda] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Agenda] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Agenda] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Agenda] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Agenda] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Agenda] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Agenda] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Agenda] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Agenda] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Agenda] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Agenda] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Agenda] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Agenda] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Agenda] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Agenda] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Agenda] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Agenda] SET  MULTI_USER 
GO

ALTER DATABASE [Agenda] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Agenda] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Agenda] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Agenda] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Agenda] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Agenda] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Agenda] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Agenda] SET  READ_WRITE 
GO



USE [Agenda]
GO

/****** Object:  Table [dbo].[Contactos]    Script Date: 4/11/2024 11:33:31 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Contactos]') AND type in (N'U'))
DROP TABLE [dbo].[Contactos]
GO

/****** Object:  Table [dbo].[Contactos]    Script Date: 4/11/2024 11:33:31 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Contactos](
	[Id] [int] NOT NULL IDENTITY(1,1),
	[Nombre] [varchar](100) NOT NULL,
	[FechaNacimiento] [date] NOT NULL,
	[Telefono] [varchar](9) NOT NULL,
	[Observaciones] [varchar](500) NULL,
 CONSTRAINT [PK_Contactos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [Agenda]
GO

INSERT INTO [dbo].[Contactos]
           ([Nombre]
           ,[FechaNacimiento]
           ,[Telefono]
           ,[Observaciones])
     VALUES
           ('Diego','2002/07/18',608310124,'Soy yo! :D'),
		   ('Esther','2002/10/23',2122022,'Una máquina.'),
		   ('Lucas','2002/02/27',12345678,'Es mi amigo, el Lucas.');
GO


